# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY.
# Run `copier update --trust` from this directory to pull template improvements.
_commit: v1.1.0
_src_path: https://git.utlas.de/eyebrowkang/ansible-development.git
author: eyebrowkang
ci_platform: github
dependency_updates: true
galaxy_collections: []
include_docker: true
include_vagrant: false
kind: role
license: MIT
min_ansible_version: 2.16.0
namespace: eyebrowkang
needs_systemd: true
release_automation: true
role_description: Install and configure Meilisearch as a systemd service on Linux
    systems
role_name: meilisearch
shell_templates: false
