---
dependency:
  name: galaxy

driver:
  name: default
  options:
    managed: true

platforms:
  - name: meilisearch-upgrade-dumpless
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    systemd: true
    groups:
      - meilisearch_servers

provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible

scenario:
  name: upgrade_dumpless
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
