---
- name: Check if Meilisearch binary exists
  ansible.builtin.stat:
    path: "{{ meilisearch_binary_path }}"
  register: meilisearch_binary

- name: Download Meilisearch binary
  ansible.builtin.include_tasks: download_binary.yml
  when: not meilisearch_binary.stat.exists
