---
- name: Validate
  ansible.builtin.include_tasks: validate.yml

- name: Resolve HTTP address
  ansible.builtin.include_tasks: resolve_http_addr.yml

- name: Setup
  ansible.builtin.include_tasks: setup.yml

- name: Version check
  ansible.builtin.include_tasks: version_check.yml
  when: meilisearch_upgrade != ""

- name: Validate upgrade-sensitive configuration
  ansible.builtin.include_tasks: validate_upgrade_config.yml
  when: meilisearch_upgrade != "" and (_meilisearch_upgrade_needed | default(false) | bool)

- name: Upgrade (dumpless)
  ansible.builtin.include_tasks: upgrade_dumpless.yml
  when: meilisearch_upgrade == "dumpless" and (_meilisearch_upgrade_needed | default(false) | bool)

- name: Upgrade (dump)
  ansible.builtin.include_tasks: upgrade_dump.yml
  when: meilisearch_upgrade == "dump" and (_meilisearch_upgrade_needed | default(false) | bool)

- name: Install
  ansible.builtin.include_tasks: install.yml
  when: meilisearch_upgrade == "" or (_meilisearch_fresh_install | default(false) | bool)

- name: Configure
  ansible.builtin.include_tasks: configure.yml

- name: Service
  ansible.builtin.include_tasks: service.yml
