---
- name: Upgrade Meilisearch via dump
  hosts: all
  become: true
  vars:
    meilisearch_version: "v1.26.0"
    meilisearch_env: "development"
    meilisearch_upgrade: "dump"
  roles:
    - role: eyebrowkang.meilisearch
